// AUTO-GENERATED by scripts/build-themes.ts
// Do not edit manually - edit overrides.ts instead

import type { ThemePalette } from './types';

export const themes: Record<string, ThemePalette> = {
  'catppuccin-frappe': {
    colors: {
      accent: '#8caaee',
      auxiliary: '#232634',
      bg: '#303446',
      emphasis: '#c6d0f5',
      error: '#e78284',
      info: '#8caaee',
      muted: '#838ba7',
      subtle: '#51576d',
      success: '#a6d189',
      surface: '#292c3c',
      text: '#c6d0f5',
      warning: '#ef9f76'
    },
    id: 'catppuccin-frappe',
    name: 'Catppuccin Frappe',
    overrides: {
      bold: '#f4b8e4',
      h1: '#ca9ee6',
      h2: '#babbf1',
      h3: '#8caaee',
      h4: '#81c8be',
      inlineCode: {
        bg: '#292c3c',
        fg: '#f2d5cf'
      },
      italic: '#99d1db'
    },
    shikiTheme: 'catppuccin-frappe',
    type: 'dark'
  },
  'catppuccin-latte': {
    colors: {
      accent: '#1e66f5',
      auxiliary: '#dce0e8',
      bg: '#eff1f5',
      emphasis: '#4c4f69',
      error: '#d20f39',
      info: '#1e66f5',
      muted: '#8c8fa1',
      subtle: '#bcc0cc',
      success: '#40a02b',
      surface: '#e6e9ef',
      text: '#4c4f69',
      warning: '#fe640b'
    },
    id: 'catppuccin-latte',
    name: 'Catppuccin Latte',
    overrides: {
      bold: '#ea76cb',
      h1: '#8839ef',
      h2: '#7287fd',
      h3: '#1e66f5',
      h4: '#179299',
      inlineCode: {
        bg: '#e6e9ef',
        fg: '#dc8a78'
      },
      italic: '#04a5e5'
    },
    shikiTheme: 'catppuccin-latte',
    type: 'light'
  },
  'catppuccin-macchiato': {
    colors: {
      accent: '#8aadf4',
      auxiliary: '#181926',
      bg: '#24273a',
      emphasis: '#cad3f5',
      error: '#ed8796',
      info: '#8aadf4',
      muted: '#8087a2',
      subtle: '#494d64',
      success: '#a6da95',
      surface: '#1e2030',
      text: '#cad3f5',
      warning: '#f5a97f'
    },
    id: 'catppuccin-macchiato',
    name: 'Catppuccin Macchiato',
    overrides: {
      bold: '#f5bde6',
      h1: '#c6a0f6',
      h2: '#b7bdf8',
      h3: '#8aadf4',
      h4: '#8bd5ca',
      inlineCode: {
        bg: '#1e2030',
        fg: '#f4dbd6'
      },
      italic: '#91d7e3'
    },
    shikiTheme: 'catppuccin-macchiato',
    type: 'dark'
  },
  'catppuccin-mocha': {
    colors: {
      accent: '#89b4fa',
      auxiliary: '#11111b',
      bg: '#1e1e2e',
      emphasis: '#cdd6f4',
      error: '#f38ba8',
      info: '#89b4fa',
      muted: '#7f849c',
      subtle: '#45475a',
      success: '#a6e3a1',
      surface: '#181825',
      text: '#cdd6f4',
      warning: '#fab387'
    },
    id: 'catppuccin-mocha',
    name: 'Catppuccin Mocha',
    overrides: {
      bold: '#f5c2e7',
      h1: '#cba6f7',
      h2: '#b4befe',
      h3: '#89b4fa',
      h4: '#94e2d5',
      inlineCode: {
        bg: '#181825',
        fg: '#f5e0dc'
      },
      italic: '#89dceb'
    },
    shikiTheme: 'catppuccin-mocha',
    type: 'dark'
  },
  dracula: {
    colors: {
      accent: '#8BE9FD',
      auxiliary: '#888888',
      bg: '#282A36',
      emphasis: '#F8F8F2',
      error: '#FF5555',
      info: '#888888',
      muted: '#6272A4',
      subtle: '#FFFFFF',
      success: '#50FA7B',
      surface: '#21222C',
      text: '#F8F8F2',
      warning: '#8BE9FD'
    },
    id: 'dracula',
    name: 'Dracula',
    overrides: {
      bold: '#ff79c6',
      h1: '#bd93f9',
      h2: '#ff79c6',
      h3: '#8be9fd',
      italic: '#8be9fd'
    },
    shikiTheme: 'dracula',
    type: 'dark'
  },
  'dracula-soft': {
    colors: {
      accent: '#97e1f1',
      auxiliary: '#888888',
      bg: '#282A36',
      emphasis: '#f6f6f4',
      error: '#ee6666',
      info: '#888888',
      muted: '#7b7f8b',
      subtle: '#FFFFFF',
      success: '#62e884',
      surface: '#262626',
      text: '#f6f6f4',
      warning: '#97e1f1'
    },
    id: 'dracula-soft',
    name: 'Dracula Soft',
    overrides: {
      bold: '#ff79c6',
      h1: '#bd93f9',
      h2: '#ff79c6',
      h3: '#8be9fd',
      italic: '#8be9fd'
    },
    shikiTheme: 'dracula-soft',
    type: 'dark'
  },
  'github-dark': {
    colors: {
      accent: '#79b8ff',
      auxiliary: '#444d56',
      bg: '#24292e',
      emphasis: '#d1d5da',
      error: '#f97583',
      info: '#79b8ff',
      muted: '#444d56',
      subtle: '#2f363d',
      success: '#34d058',
      surface: '#1f2428',
      text: '#e1e4e8',
      warning: '#ffea7f'
    },
    id: 'github-dark',
    name: 'GitHub Dark',
    shikiTheme: 'github-dark',
    type: 'dark'
  },
  'github-dark-default': {
    colors: {
      accent: '#2f81f7',
      auxiliary: '#30363d',
      bg: '#0d1117',
      emphasis: '#7d8590',
      error: '#f85149',
      info: '#2f81f7',
      muted: '#6e7681',
      subtle: '#e6edf3',
      success: '#3fb950',
      surface: '#161b22',
      text: '#e6edf3',
      warning: '#888888'
    },
    id: 'github-dark-default',
    name: 'GitHub Dark Default',
    shikiTheme: 'github-dark-default',
    type: 'dark'
  },
  'github-dark-dimmed': {
    colors: {
      accent: '#539bf5',
      auxiliary: '#444c56',
      bg: '#22272e',
      emphasis: '#768390',
      error: '#e5534b',
      info: '#539bf5',
      muted: '#636e7b',
      subtle: '#adbac7',
      success: '#57ab5a',
      surface: '#2d333b',
      text: '#adbac7',
      warning: '#888888'
    },
    id: 'github-dark-dimmed',
    name: 'GitHub Dark Dimmed',
    shikiTheme: 'github-dark-dimmed',
    type: 'dark'
  },
  'github-dark-high-contrast': {
    colors: {
      accent: '#71b7ff',
      auxiliary: '#7a828e',
      bg: '#0a0c10',
      emphasis: '#f0f3f6',
      error: '#ff6a69',
      info: '#71b7ff',
      muted: '#9ea7b3',
      subtle: '#f0f3f6',
      success: '#26cd4d',
      surface: '#272b33',
      text: '#f0f3f6',
      warning: '#888888'
    },
    id: 'github-dark-high-contrast',
    name: 'GitHub Dark High Contrast',
    shikiTheme: 'github-dark-high-contrast',
    type: 'dark'
  },
  'github-light': {
    colors: {
      accent: '#0366d6',
      auxiliary: '#e1e4e8',
      bg: '#fff',
      emphasis: '#586069',
      error: '#cb2431',
      info: '#0366d6',
      muted: '#1b1f23',
      subtle: '#eff2f6',
      success: '#28a745',
      surface: '#f6f8fa',
      text: '#24292e',
      warning: '#f9c513'
    },
    id: 'github-light',
    name: 'GitHub Light',
    shikiTheme: 'github-light',
    type: 'light'
  },
  'github-light-default': {
    colors: {
      accent: '#0969da',
      auxiliary: '#d0d7de',
      bg: '#ffffff',
      emphasis: '#656d76',
      error: '#cf222e',
      info: '#0969da',
      muted: '#8c959f',
      subtle: '#1f2328',
      success: '#1a7f37',
      surface: '#ffffff',
      text: '#1f2328',
      warning: '#888888'
    },
    id: 'github-light-default',
    name: 'GitHub Light Default',
    shikiTheme: 'github-light-default',
    type: 'light'
  },
  'github-light-high-contrast': {
    colors: {
      accent: '#0349b4',
      auxiliary: '#20252c',
      bg: '#ffffff',
      emphasis: '#0e1116',
      error: '#a0111f',
      info: '#0349b4',
      muted: '#88929d',
      subtle: '#0e1116',
      success: '#055d20',
      surface: '#ffffff',
      text: '#0e1116',
      warning: '#888888'
    },
    id: 'github-light-high-contrast',
    name: 'GitHub Light High Contrast',
    shikiTheme: 'github-light-high-contrast',
    type: 'light'
  },
  'gruvbox-dark-hard': {
    colors: {
      accent: '#83a598',
      auxiliary: '#83a598',
      bg: '#1d2021',
      emphasis: '#ebdbb2',
      error: '#fb4934',
      info: '#458588',
      muted: '#665c54',
      subtle: '#a89984',
      success: '#ebdbb2',
      surface: '#1d2021',
      text: '#ebdbb2',
      warning: '#d79921'
    },
    id: 'gruvbox-dark-hard',
    name: 'Gruvbox Dark Hard',
    shikiTheme: 'gruvbox-dark-hard',
    type: 'dark'
  },
  'gruvbox-dark-medium': {
    colors: {
      accent: '#83a598',
      auxiliary: '#83a598',
      bg: '#282828',
      emphasis: '#ebdbb2',
      error: '#fb4934',
      info: '#458588',
      muted: '#665c54',
      subtle: '#a89984',
      success: '#ebdbb2',
      surface: '#282828',
      text: '#ebdbb2',
      warning: '#d79921'
    },
    id: 'gruvbox-dark-medium',
    name: 'Gruvbox Dark Medium',
    shikiTheme: 'gruvbox-dark-medium',
    type: 'dark'
  },
  'gruvbox-dark-soft': {
    colors: {
      accent: '#83a598',
      auxiliary: '#83a598',
      bg: '#32302f',
      emphasis: '#ebdbb2',
      error: '#fb4934',
      info: '#458588',
      muted: '#665c54',
      subtle: '#a89984',
      success: '#ebdbb2',
      surface: '#32302f',
      text: '#ebdbb2',
      warning: '#d79921'
    },
    id: 'gruvbox-dark-soft',
    name: 'Gruvbox Dark Soft',
    shikiTheme: 'gruvbox-dark-soft',
    type: 'dark'
  },
  'gruvbox-light-hard': {
    colors: {
      accent: '#076678',
      auxiliary: '#076678',
      bg: '#f9f5d7',
      emphasis: '#3c3836',
      error: '#9d0006',
      info: '#458588',
      muted: '#bdae93',
      subtle: '#7c6f64',
      success: '#3c3836',
      surface: '#f9f5d7',
      text: '#3c3836',
      warning: '#d79921'
    },
    id: 'gruvbox-light-hard',
    name: 'Gruvbox Light Hard',
    shikiTheme: 'gruvbox-light-hard',
    type: 'light'
  },
  'gruvbox-light-medium': {
    colors: {
      accent: '#076678',
      auxiliary: '#076678',
      bg: '#fbf1c7',
      emphasis: '#3c3836',
      error: '#9d0006',
      info: '#458588',
      muted: '#bdae93',
      subtle: '#7c6f64',
      success: '#3c3836',
      surface: '#fbf1c7',
      text: '#3c3836',
      warning: '#d79921'
    },
    id: 'gruvbox-light-medium',
    name: 'Gruvbox Light Medium',
    shikiTheme: 'gruvbox-light-medium',
    type: 'light'
  },
  'gruvbox-light-soft': {
    colors: {
      accent: '#076678',
      auxiliary: '#076678',
      bg: '#f2e5bc',
      emphasis: '#3c3836',
      error: '#9d0006',
      info: '#458588',
      muted: '#bdae93',
      subtle: '#7c6f64',
      success: '#3c3836',
      surface: '#f2e5bc',
      text: '#3c3836',
      warning: '#d79921'
    },
    id: 'gruvbox-light-soft',
    name: 'Gruvbox Light Soft',
    shikiTheme: 'gruvbox-light-soft',
    type: 'light'
  },
  'material-theme': {
    colors: {
      accent: '#80CBC4',
      auxiliary: '#80CBC4',
      bg: '#263238',
      emphasis: '#EEFFFF',
      error: '#f07178',
      info: '#82AAFF',
      muted: '#465A64',
      subtle: '#37474F',
      success: '#C3E88D',
      surface: '#263238',
      text: '#EEFFFF',
      warning: '#FFCB6B'
    },
    id: 'material-theme',
    name: 'Material Theme',
    shikiTheme: 'material-theme',
    type: 'dark'
  },
  'material-theme-darker': {
    colors: {
      accent: '#80CBC4',
      auxiliary: '#80CBC4',
      bg: '#212121',
      emphasis: '#EEFFFF',
      error: '#f07178',
      info: '#82AAFF',
      muted: '#424242',
      subtle: '#424242',
      success: '#C3E88D',
      surface: '#212121',
      text: '#EEFFFF',
      warning: '#FFCB6B'
    },
    id: 'material-theme-darker',
    name: 'Material Theme Darker',
    shikiTheme: 'material-theme-darker',
    type: 'dark'
  },
  'material-theme-lighter': {
    colors: {
      accent: '#80CBC4',
      auxiliary: '#80CBC4',
      bg: '#FAFAFA',
      emphasis: '#90A4AE',
      error: '#E53935',
      info: '#6182B8',
      muted: '#CFD8DC',
      subtle: '#B0BEC5',
      success: '#91B859',
      surface: '#FAFAFA',
      text: '#90A4AE',
      warning: '#E2931D'
    },
    id: 'material-theme-lighter',
    name: 'Material Theme Lighter',
    shikiTheme: 'material-theme-lighter',
    type: 'light'
  },
  'material-theme-ocean': {
    colors: {
      accent: '#80CBC4',
      auxiliary: '#80CBC4',
      bg: '#0F111A',
      emphasis: '#babed8',
      error: '#f07178',
      info: '#82AAFF',
      muted: '#3B3F51',
      subtle: '#3B3F51',
      success: '#C3E88D',
      surface: '#0F111A',
      text: '#babed8',
      warning: '#FFCB6B'
    },
    id: 'material-theme-ocean',
    name: 'Material Theme Ocean',
    shikiTheme: 'material-theme-ocean',
    type: 'dark'
  },
  'material-theme-palenight': {
    colors: {
      accent: '#80CBC4',
      auxiliary: '#80CBC4',
      bg: '#292D3E',
      emphasis: '#babed8',
      error: '#f07178',
      info: '#82AAFF',
      muted: '#3A3F58',
      subtle: '#4E5579',
      success: '#C3E88D',
      surface: '#292D3E',
      text: '#babed8',
      warning: '#FFCB6B'
    },
    id: 'material-theme-palenight',
    name: 'Material Theme Palenight',
    shikiTheme: 'material-theme-palenight',
    type: 'dark'
  },
  nord: {
    colors: {
      accent: '#88c0d0',
      auxiliary: '#81a1c1',
      bg: '#2e3440',
      emphasis: '#8fbcbb',
      error: '#bf616a',
      info: '#88c0d0',
      muted: '#4c566a',
      subtle: '#434c5e',
      success: '#a3be8c',
      surface: '#2e3440',
      text: '#d8dee9',
      warning: '#ebcb8b'
    },
    id: 'nord',
    name: 'Nord',
    overrides: {
      bold: '#88c0d0',
      h1: '#88c0d0',
      h2: '#81a1c1',
      h3: '#5e81ac',
      italic: '#81a1c1'
    },
    shikiTheme: 'nord',
    type: 'dark'
  },
  'one-dark-pro': {
    colors: {
      accent: '#61afef',
      auxiliary: '#4b5362',
      bg: '#282c34',
      emphasis: '#d19a66',
      error: '#c24038',
      info: '#61afef',
      muted: '#495162',
      subtle: '#abb2bf',
      success: '#8cc265',
      surface: '#21252b',
      text: '#abb2bf',
      warning: '#d19a66'
    },
    id: 'one-dark-pro',
    name: 'One Dark Pro',
    shikiTheme: 'one-dark-pro',
    type: 'dark'
  },
  'one-light': {
    colors: {
      accent: '#526FFF',
      auxiliary: '#888888',
      bg: '#FAFAFA',
      emphasis: '#383A42',
      error: '#888888',
      info: '#888888',
      muted: '#9D9D9F',
      subtle: '#383A42',
      success: '#888888',
      surface: '#EAEAEB',
      text: '#383A42',
      warning: '#888888'
    },
    id: 'one-light',
    name: 'One Light',
    shikiTheme: 'one-light',
    type: 'light'
  },
  'rose-pine': {
    colors: {
      accent: '#c4a7e7',
      auxiliary: '#6e6a86',
      bg: '#191724',
      emphasis: '#f6c177',
      error: '#eb6f92',
      info: '#9ccfd8',
      muted: '#908caa',
      subtle: '#6e6a86',
      success: '#9ccfd8',
      surface: '#1f1d2e',
      text: '#e0def4',
      warning: '#f6c177'
    },
    id: 'rose-pine',
    name: 'Rose Pine',
    overrides: {
      bold: '#ebbcba',
      h1: '#c4a7e7',
      h2: '#ebbcba',
      h3: '#9ccfd8',
      italic: '#9ccfd8'
    },
    shikiTheme: 'rose-pine',
    type: 'dark'
  },
  'rose-pine-dawn': {
    colors: {
      accent: '#907aa9',
      auxiliary: '#6e6a86',
      bg: '#faf4ed',
      emphasis: '#ea9d34',
      error: '#b4637a',
      info: '#56949f',
      muted: '#797593',
      subtle: '#6e6a86',
      success: '#56949f',
      surface: '#fffaf3',
      text: '#575279',
      warning: '#ea9d34'
    },
    id: 'rose-pine-dawn',
    name: 'Rose Pine Dawn',
    overrides: {
      bold: '#d7827e',
      h1: '#907aa9',
      h2: '#d7827e',
      h3: '#56949f',
      italic: '#56949f'
    },
    shikiTheme: 'rose-pine-dawn',
    type: 'light'
  },
  'rose-pine-moon': {
    colors: {
      accent: '#c4a7e7',
      auxiliary: '#817c9c',
      bg: '#232136',
      emphasis: '#f6c177',
      error: '#eb6f92',
      info: '#9ccfd8',
      muted: '#908caa',
      subtle: '#817c9c',
      success: '#9ccfd8',
      surface: '#2a273f',
      text: '#e0def4',
      warning: '#f6c177'
    },
    id: 'rose-pine-moon',
    name: 'Rose Pine Moon',
    overrides: {
      bold: '#ebbcba',
      h1: '#c4a7e7',
      h2: '#ebbcba',
      h3: '#9ccfd8',
      italic: '#9ccfd8'
    },
    shikiTheme: 'rose-pine-moon',
    type: 'dark'
  },
  'solarized-dark': {
    colors: {
      accent: '#2AA198',
      auxiliary: '#888888',
      bg: '#002B36',
      emphasis: '#839496',
      error: '#ffeaea',
      info: '#888888',
      muted: '#888888',
      subtle: '#93A1A1',
      success: '#859900',
      surface: '#00212B',
      text: '#839496',
      warning: '#888888'
    },
    id: 'solarized-dark',
    name: 'Solarized Dark',
    shikiTheme: 'solarized-dark',
    type: 'dark'
  },
  'solarized-light': {
    colors: {
      accent: '#b49471',
      auxiliary: '#888888',
      bg: '#FDF6E3',
      emphasis: '#657B83',
      error: '#888888',
      info: '#888888',
      muted: '#888888',
      subtle: '#586E75',
      success: '#859900',
      surface: '#EEE8D5',
      text: '#657B83',
      warning: '#888888'
    },
    id: 'solarized-light',
    name: 'Solarized Light',
    shikiTheme: 'solarized-light',
    type: 'light'
  },
  'tokyo-night': {
    colors: {
      accent: '#6183bb',
      auxiliary: '#6183bb',
      bg: '#1a1b26',
      emphasis: '#9699a8',
      error: '#515670',
      info: '#0da0ba',
      muted: '#363b54',
      subtle: '#101014',
      success: '#449dab',
      surface: '#16161e',
      text: '#a9b1d6',
      warning: '#e0af68'
    },
    id: 'tokyo-night',
    name: 'Tokyo Night',
    overrides: {
      bold: '#bb9af7',
      h1: '#bb9af7',
      h2: '#7aa2f7',
      h3: '#7dcfff',
      italic: '#7dcfff'
    },
    shikiTheme: 'tokyo-night',
    type: 'dark'
  }
};

export const themeIds = [
  'catppuccin-frappe',
  'catppuccin-latte',
  'catppuccin-macchiato',
  'catppuccin-mocha',
  'nord',
  'dracula',
  'dracula-soft',
  'gruvbox-dark-hard',
  'gruvbox-dark-medium',
  'gruvbox-dark-soft',
  'gruvbox-light-hard',
  'gruvbox-light-medium',
  'gruvbox-light-soft',
  'solarized-dark',
  'solarized-light',
  'tokyo-night',
  'one-dark-pro',
  'one-light',
  'github-dark',
  'github-dark-default',
  'github-dark-dimmed',
  'github-dark-high-contrast',
  'github-light',
  'github-light-default',
  'github-light-high-contrast',
  'rose-pine',
  'rose-pine-dawn',
  'rose-pine-moon',
  'material-theme',
  'material-theme-darker',
  'material-theme-lighter',
  'material-theme-ocean',
  'material-theme-palenight'
] as const;

export type ThemeId = (typeof themeIds)[number];
